{
 "title": "Specific Spinnaker Application Details",
 "tags": [ "spinnaker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "spinSvc", "query": "orca" },
   {
    "name": "Application",
    "query": "label_values(stage_invocations_total{spinSvc=\"$spinSvc\"}, application)"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Stages by Application (orca, $Application)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(stage_invocations_total{spinSvc=\"$spinSvc\", application=~\"$Application\"}[$__interval])) by (application, type)",
     "legendFormat": "{{application}}/{{type}}"
    }
   ]
  },
  {
   "title": "Pushed Messages by Application (orca, $Application)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(queue_pushed_messages_total{spinSvc=\"$spinSvc\", application=~\"$Application\"}[$__interval])) by (application)",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "$Application Pipelines Triggered (echo)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pipelines_triggered_total{spinSvc=~\"echo\", application=~\"$Application\"}[$__interval])) by (name, application)",
     "legendFormat": "{{name}}({{application}})"
    }
   ]
  },
  {
   "title": "Bake Requests and Failures (rosco)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(bakesActive)", "legendFormat": "Active" },
    {
     "expr": "sum(rate(bakesRequested[$__interval])) by (flavor)",
     "legendFormat": "Request({{flavor}})"
    },
    {
     "expr": "-1 * sum(rate(bakesCompleted_seconds_count{success=\"false\"}[$__interval])) by (region)",
     "legendFormat": "Failed {{region}}"
    }
   ]
  },
  {
   "title": "Bakes Completed (rosco)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bakesCompleted_seconds_sum[$__interval]) / 1000000000) by (region)\n/\nsum(rate(bakesCompleted_seconds_count[$__interval])) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Hystrix Short Circuited (global)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"open\"}) by (metricGroup, metricType, spinSvc)",
     "legendFormat": "{{spinSvc}}"
    }
   ]
  },
  {
   "title": "Hystrix Failure Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(resilience4j_circuitbreaker_failure_rate[$__interval])) by (name, spinSvc)",
     "legendFormat": "{{spinSvc}}-{{name}}"
    }
   ]
  }
 ]
}