{
 "title": "Clouddriver Microservice",
 "tags": [ "spinnaker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "spinSvc", "query": "clouddriver" },
   {
    "name": "job",
    "query": "label_values(up{job=~\".*$spinSvc.*\"}, job)"
   },
   {
    "name": "Instance",
    "query": "label_values(up{job=~\"$job\"}, instance)"
   },
   {
    "name": "Account",
    "query": "label_values(controller_invocations_total{job=~\"$job\"}, account)"
   },
   {
    "name": "Platform",
    "query": "google,aws,kubernetes,docker,appengine,dcos"
   }
  ]
 },
 "panels": [
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$Account 5xx Errors (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_total{job=~\"$job\",instance=~\"$Instance\",status=\"5xx\",account=~\"$Account\"}[$__interval])) by (controller, method, statusCode)",
     "legendFormat": "{{statusCode}}/{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Validation Errors",
   "type": "graph",
   "description": "TODO: Confirm actual metric name",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "validationErrors_total" }
   ]
  },
  { "title": "Operations and Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "$Account Controller Invocation by Method (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_total{job=~\"$job\", instance=~\"$Instance\",account=~\"$Account\"}[$__interval])) by (controller, method)",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Operation Failures by Operation (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(operations_seconds_sum{success!=\"true\"}[$__interval])) by (OperationType)\n/\nsum(rate(operations_seconds_count[$__interval])) by (OperationType)",
     "legendFormat": "{{OperationType}}"
    }
   ]
  },
  {
   "title": "$Account Controller Invocation Latency by Method (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_seconds_sum{job=~\"$job\", instance=~\"$Instance\",account=~\"$Account\"}[$__interval])) by (controller, method) \n/\nsum(rate(controller_invocations_seconds_count{job=~\"$job\", instance=~\"$Instance\",account=~\"$Account\"}[$__interval])) by (controller, method)",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Tasks per Instance (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tasks_total{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Operations by Operation (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(operations_seconds_count{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (OperationType)",
     "legendFormat": "{{OperationType}}"
    }
   ]
  },
  {
   "title": "Execution Count by Instance (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(executionCount_total{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Operation Time by Operation (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(operations_seconds_sum{job=~\"$job\",instance=~\"$Instance\"}[$__interval])) by (OperationType)\n/\nsum(rate(operations_seconds_count{job=~\"$job\",instance=~\"$Instance\"}[$__interval])) by (OperationType)",
     "legendFormat": "{{OperationType}}"
    }
   ]
  },
  {
   "title": "Execution Latency by Instance (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(executionTime_seconds_sum{job=~\"$job\",instance=~\"$Instance\"}[$__interval])) by (instance)\n/\nsum(rate(executionTime_seconds_count{job=~\"$job\",instance=~\"$Instance\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Platform Caching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "On Demand Reads by Type (clouddriver, $Instance, $Platform)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(onDemand_read_seconds_count{job=~\"$job\",providerName=~\".*$Platform.*\", instance=~\"$Instance\"}[$__interval])) by (onDemandType)",
     "legendFormat": "{{onDemandType}}"
    }
   ]
  },
  {
   "title": "Cache Agent Execution by Account (clouddriver, $Instance, $Platform)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (provider, account) (\n# provider\nlabel_replace(\n# account\nlabel_replace(\n# query\n(sum(rate(executionTime_seconds_count{job=~\"$job\", agent=~\".*$Platform.*\",instance=~\"$Instance\"}[$__interval])) by (agent)\n),\n\"account\", \"$1\", \"agent\", \"^[A-Za-z]+/([A-Za-z0-9-]+).*\"\n), \n\"provider\", \"$1\", \"agent\", \"^([A-Za-z]+).*\"\n)\n)",
     "legendFormat": "{{ provider }} :: {{ account }}"
    }
   ]
  },
  {
   "title": "On Demand Read Latency by Type (clouddriver, $Instance, $Platform)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(onDemand_read_seconds_sum{job=~\"$job\",providerName=~\".*$Platform.*\", instance=~\"$Instance\"}[$__interval])) by (onDemandType)\n/\nsum(rate(onDemand_read_seconds_count{job=~\"$job\",providerName=~\".*$Platform.*\", instance=~\"$Instance\"}[$__interval])) by (onDemandType)",
     "legendFormat": "{{onDemandType}}"
    }
   ]
  },
  {
   "title": "Cache Agent Execution Latency by Account (clouddriver, $Instance, $Platform)",
   "type": "graph",
   "description": "TODO: Double check - numbers look wrong",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (provider, account) (\n# provider\nlabel_replace(\n# account\nlabel_replace(\n# query\n(sum(rate(executionTime_seconds_sum{job=~\"$job\", agent=~\".*$Platform.*\",instance=~\"$Instance\"}[$__interval])) by (agent)\n),\n\"account\", \"$1\", \"agent\", \"^[A-Za-z]+/([A-Za-z0-9-]+).*\"\n), \n\"provider\", \"$1\", \"agent\", \"^([A-Za-z]+).*\"\n)\n)\n\n/\n\nsum by (provider, account) (\n# provider\nlabel_replace(\n# account\nlabel_replace(\n# query\n(sum(rate(executionTime_seconds_count{job=~\"$job\", agent=~\".*$Platform.*\",instance=~\"$Instance\"}[$__interval])) by (agent)\n),\n\"account\", \"$1\", \"agent\", \"^[A-Za-z]+/([A-Za-z0-9-]+).*\"\n), \n\"provider\", \"$1\", \"agent\", \"^([A-Za-z]+).*\"\n)\n)",
     "legendFormat": "{{ provider }} :: {{ account }}"
    }
   ]
  },
  { "title": "SQL Caching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "CATS Relationships Requested by Platform (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_get_relationshipsRequested_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_get_relationshipsRequested_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Relationships Requested by Type (clouddriver, $Instance, $Platform)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cats_sqlCache_get_relationshipsRequested_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CATS Items Requested by Platform (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_get_itemCount_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_get_itemCount_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Items Requested by Type (clouddriver, $Instance, $Platform)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cats_sqlCache_get_itemCount_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CATS Relationships Written by Platform (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_merge_relationshipCount_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_merge_relationshipCount_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Relationships Written by Type (clouddriver, $Instance, $Platform)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cats_sqlCache_merge_relationshipCount_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CATS Items Written by Platform (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_merge_itemCount_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_merge_itemCount_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Items Written by Type (clouddriver, $Instance, $Platform)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cats_sqlCache_merge_itemCount_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CATS Items Deleted by Platform (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_evict_itemCount_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_sqlCache_evict_itemCount_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Items Deleted by Type (clouddriver, $Instance, $Platform)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cats_sqlCache_evict_itemCount_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Redis Caching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "CATS Keys Requested by Platform (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_redisCache_get_keysRequested_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_redisCache_get_keysRequested_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Keys Requested by Type (clouddriver, $Instance, $Platform)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cats_redisCache_get_keysRequested_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CATS Items Requested by Platform (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_redisCache_get_itemCount_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_redisCache_get_itemCount_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Items Requested by Type (clouddriver, $Instance, $Platform)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cats_redisCache_get_itemCount_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CATS Keys Written by Platform (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_redisCache_merge_keysWritten_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_redisCache_merge_keysWritten_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Keys Written by Type (clouddriver, $Instance, $Platform)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cats_redisCache_merge_keysWritten_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CATS Items Written by Platform (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_redisCache_merge_itemCount_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_redisCache_merge_itemCount_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Items Written by Type (clouddriver, $Instance, $Platform)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cats_redisCache_merge_itemCount_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CATS Keys Deleted by Platform (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_redisCache_evict_itemCount_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_redisCache_evict_itemCount_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Keys Deleted by Type (clouddriver, $Instance, $Platform)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cats_redisCache_evict_keysDeleted_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CATS Items Deleted by Platform (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(cats_redisCache_evict_itemCount_total{prefix=~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \".*.clouddriver.([^\\\\.]*).*\")",
     "legendFormat": "{{platform}}"
    },
    {
     "expr": "label_replace(sum(rate(cats_redisCache_evict_itemCount_total{prefix!~\"com.netflix.*\", instance=~\"$Instance\"}[$__interval])) by (prefix), \"platform\", \"$1\", \"prefix\", \"([^\\\\./]*).*\")",
     "legendFormat": "{{platform}}"
    }
   ]
  },
  {
   "title": "CATS Items Deleted by Type (clouddriver, $Instance, $Platform)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cats_redisCache_evict_itemCount_total{prefix=~\".*.$Platform.*\", instance=~\"$Instance\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "TODO - Google Operations - Confirm metric names",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 }
  },
  {
   "title": "Google Operation Failures (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(clouddriver:google:operationWaits__count_total{instance=~\"$Instance\",status!=\"DONE\"}[$__interval])) by (basePhase, scope) ",
     "legendFormat": "{{scope}}/{{basePhase}}"
    }
   ]
  },
  {
   "title": "Google Operation Wait Until Done Time (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(rate(clouddriver:google:operationWaits__totalTime_total{instance=~\"$Instance\"}[$__interval])) by (basePhase, scope) / sum(rate(clouddriver:google:operationWaits__count_total{instance=~\"$Instance\"}[$__interval])) by (basePhase, scope) ",
     "legendFormat": "{{scope}}/{{basePhase}}"
    }
   ]
  },
  {
   "title": "Google Operations Started (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "clouddriver:google:operationWaitRequests",
     "legendFormat": "{{scope}}/{{basePhase}}"
    }
   ]
  },
  {
   "title": "Google Operation Success (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(clouddriver:google:operationWaits__count_total{instance=~\"$Instance\",status=\"DONE\"}[$__interval])) by (basePhase)",
     "legendFormat": "{{basePhase}}"
    }
   ]
  },
  { "title": "Amazon Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Amazon Client Rate Limiting by ClientType (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(amazonClientProvider_rateLimitDelayMil[$__interval])) by (clientType)",
     "legendFormat": "{{clientType}}"
    }
   ]
  },
  {
   "title": "$Account Cache Drift by Region/Agent (clouddriver, $Instance)",
   "type": "graph",
   "description": "TODO: Confirm metric - no values in Prometheus",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(\n# query\navg(cache_drift{account=~\"$Account\", instance=~\"$Instance\"}) by (account, agent, region),\n\"agent\", \"$1\", \"agent\",  \"(.*)CachingAgent\"\n)",
     "legendFormat": "{{account}}/{{region}}/{{agent}}"
    }
   ]
  },
  { "title": "Machine Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "JVM Memory Usage (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$job\", instance=~\"$Instance\", area=\"heap\"}) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}