{
 "title": "Fiat Microservice",
 "tags": [ "spinnaker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "query": "fiat" },
   {
    "name": "Instance",
    "query": "label_values(up{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "5xx Controller Invocations (fiat, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_total{job=~\"$job\", instance=~\"$Instance\",status=\"5xx\"}[$__interval])) by (controller, method, statusCode)",
     "legendFormat": "{{statusCode}}/{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Controller Invocations by Method (fiat, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_total{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (controller, method)",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Controller Invocation Latency by Method (fiat, $Instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_seconds_sum{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (controller, method)\n/\nsum(rate(controller_invocations_seconds_count{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (controller, method)",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage (fiat, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$job\", instance=~\"$Instance\", area=\"heap\"}) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}