{
 "title": "Front50 Microservice",
 "tags": [ "spinnaker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "spinSvc", "query": "front50" },
   {
    "name": "job",
    "query": "label_values(up{job=~\".*$spinSvc.*\"}, job)"
   },
   {
    "name": "Instance",
    "query": "label_values(up{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Resilience4J Open (front50, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{job=~\"$job\", state=~\".*open\", instance=~\"$Instance\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resilience4J Failure Rate (front50, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(resilience4j_circuitbreaker_failure_rate{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Resilience4J Half-Open (front50, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{job=~\"$job\", state=\"half_open\", instance=~\"$Instance\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "5xx Invocation Errors by Method (front50, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_total{job=~\"$job\", instance=~\"$Instance\", status=\"5xx\"}[$__interval])) by (controller, method, statusCode)",
     "legendFormat": "{{statusCode}}/{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Cache Refreshes / Minute  (negative are scheduled) (front50, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storageServiceSupport_autoRefreshTime_seconds_sum{instance=~\"$Instance\"}[$__interval])) by (objectType)",
     "legendFormat": "force/{{objectType}}"
    },
    {
     "expr": "-1 * (sum(rate(storageServiceSupport_scheduledRefreshTime_seconds_sum{instance=~\"$Instance\"}[$__interval])) by (objectType))",
     "legendFormat": "{{objectType}}"
    }
   ]
  },
  {
   "title": "Controller Invocation by Method (front50, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_total{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (controller, method)",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Item Cache Size (front50, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(storageServiceSupport_cacheSize{instance=~\"$Instance\"}) by (objectType)",
     "legendFormat": "{{objectType}}"
    }
   ]
  },
  {
   "title": "Controller Invocation Latency by Method (front50, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_seconds_sum{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (controller, method)\n/ \nsum(rate(controller_invocations_seconds_count{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (controller, method)",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Item Cache Adds (+) and Removes (-) (front50, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storageServiceSupport_numAdded_total{instance=~\"$Instance\"}[$__interval])) by (objectType)",
     "legendFormat": "add {{objectType}}"
    },
    {
     "expr": "-1 * sum(rate(storageServiceSupport_numRemoved_total{instance=~\"$Instance\"}[$__interval])) by (objectType)",
     "legendFormat": "del {{objectType}}"
    }
   ]
  },
  {
   "title": "Google Storage Service Invocations (front50, $Instance)",
   "type": "graph",
   "description": "TODO: Swap for relevant SQL metrics?",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(front50:google:storage:invocation__count_total{instance=~\"$Instance\"}[$__interval])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Item Cache Updates (front50, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storageServiceSupport_numUpdated_total{instance=~\"$Instance\"}[$__interval])) by (objectType)",
     "legendFormat": "{{objectType}}"
    }
   ]
  },
  {
   "title": "Google Storage Service Invocation Latency (front50, $Instance)",
   "type": "graph",
   "description": "TODO: Swap for relevant SQL metrics?",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(rate(front50:google:storage:invocation__totalTime_total{instance=~\"$Instance\"}[$__interval])) by (method) / sum(rate(front50:google:storage:invocation__count_total{instance=~\"$Instance\"}[$__interval])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Item Cache Age (front50, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (objectType) (storageServiceSupport_cacheAge{instance=~\"$Instance\"})",
     "legendFormat": "{{objectType}}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage (front50, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{job=~\"$job\", instance=~\"$Instance\",area=\"heap\"}) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}