{
 "title": "Gate Microservice",
 "description": "TODO: Scrape metrics without OAUTH",
 "tags": [ "spinnaker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "spinSvc", "query": "gate" },
   {
    "name": "job",
    "query": "label_values(up{job=~\".*$spinSvc.*\"}, job)"
   },
   {
    "name": "Instance",
    "query": "label_values(up{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Resilience4J Open (gate, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{job=~\"$job\", state=~\".*open\", instance=~\"$Instance\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resilience4J Failure Rate (gate, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(resilience4j_circuitbreaker_failure_rate{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Resilience4J Half-Open (gate, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{job=~\"$job\", state=\"half_open\", instance=~\"$Instance\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Rate Limit Throttling (gate, $Instance)",
   "type": "graph",
   "description": "TODO: Confirm metric name",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rateLimitThrottling_total{instance=~\"$Instance\"}[$__interval])"
    }
   ]
  },
  {
   "title": "5xx/429 Controller Invocations (gate, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_seconds_count{job=~\"$job\", instance=~\"$Instance\",status=\"5xx\"}[$__interval])) by (controller, method, statusCode)",
     "legendFormat": "{{statusCode}}/{{controller}}/{{method}}"
    },
    {
     "expr": "sum(rate(controller_invocations_seconds_count{job=~\"$job\", instance=~\"$Instance\",statusCode=\"429\"}[$__interval])) by (controller, method, statusCode)",
     "legendFormat": "{{statusCode}}/{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Controller Invocations by Method (gate, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_seconds_count{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (controller, method)",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Controller Invocation Latency by Method (gate, $Instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_seconds_sum{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (controller, method)\n/\nsum(rate(controller_invocations_seconds_count{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (controller, method)",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage (gate, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$job\", instance=~\"$Instance\", area=\"heap\"}) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}