{
 "title": "Spinnaker GCP Details",
 "tags": [
  "spinnaker",
  "google"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "GcpRegion", "query": "clouddriver:google:api__count" },
   {
    "name": "Instance",
    "label": "Clouddriver",
    "query": "label_values(clouddriver:google:api__count, instance)"
   },
   {
    "name": "Front50Instance",
    "label": "Front50",
    "query": "label_values(front50:google:storage:invocation__count, instance)"
   }
  ]
 },
 "panels": [
  { "title": "API Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GCP API Failures by Resource (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(clouddriver:google:api__count_total{instance=~\"$Instance\",status!=\"2xx\"}[$__interval]), \"resource\", \"$1\", \"api\", \"compute.(.*)\\\\..*\")) by (resource, statusCode)",
     "legendFormat": "{{statusCode}}/{{resource}}"
    }
   ]
  },
  {
   "title": "GCP API Failures by Region (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(clouddriver:google:api__count_total{instance=~\"$Instance\",status!=\"2xx\", scope=\"regional\"}[$__interval])) by (region, statusCode)",
     "legendFormat": "{{statusCode}}/{{region}}"
    },
    {
     "expr": "sum(label_replace(rate(clouddriver:google:api__count_total{instance=~\"$Instance\",status!=\"2xx\",scope=\"zonal\"}[$__interval]), \"zoneRegion\", \"$1\", \"zone\", \"(.*)-.\")) by (zoneRegion, statusCode)",
     "legendFormat": "{{statusCode}}/{{zoneRegion}}+"
    },
    {
     "expr": "sum(rate(clouddriver:google:api__count_total{instance=~\"$Instance\",status!=\"2xx\",scope=\"global\"}[$__interval])) by (zone, statusCode)",
     "legendFormat": "{{statusCode}}/global"
    }
   ]
  },
  {
   "title": "Google Storage Failures By Method (front50, $Front50Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(front50:google:storage:invocation__count_total{instance=~\"$Front50Instance\",status!=\"2xx\"}[$__interval])) by (method, statusCode)",
     "legendFormat": "{{statusCode}}/{{method}}"
    }
   ]
  },
  {
   "title": "Google Storage Retry Failures by Method (front50, $Front50Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(front50:google:safeRetry__count_total{instance=~\"$Front50Instance\", success!=\"true\"}[$__interval])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  { "title": "API Call Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "GCP API Calls by Resource (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(clouddriver:google:api__count_total{instance=~\"$Instance\"}[$__interval]), \"resource\", \"$1\", \"api\", \"compute.(.*)\\\\..*\")) by (resource, status, statusCode)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "GCP API Calls by Region (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(clouddriver:google:api__count_total{instance=~\"$Instance\",scope=\"regional\"}[$__interval])) by (region)",
     "legendFormat": "{{region}}"
    },
    {
     "expr": "sum(label_replace(rate(clouddriver:google:api__count_total{instance=~\"$Instance\",scope=\"zonal\"}[$__interval]), \"zoneRegion\", \"$1\", \"zone\", \"(.*)-.\")) by (zoneRegion)",
     "legendFormat": "{{zoneRegion}}+"
    },
    {
     "expr": "sum(rate(clouddriver:google:api__count_total{instance=~\"$Instance\",scope=\"global\"}[$__interval])) by (zone)",
     "legendFormat": "global"
    }
   ]
  },
  { "title": "Global API Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Global GCP API Calls (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(clouddriver:google:api__count_total{instance=~\"$Instance\",scope=\"global\"}[$__interval])) by (api), \"api\", \"$1\", \"api\", \"compute.(.*)\")",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Global GCP API Latency (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(clouddriver:google:api__totalTime_total{instance=~\"$Instance\",scope=\"global\"}[$__interval])) by (api) / sum(rate(clouddriver:google:api__count_total{instance=~\"$Instance\",scope=\"global\"}[$__interval])) by (api), \"api\", \"$1\", \"api\", \"compute.(.*)\")",
     "legendFormat": "{{api}}"
    }
   ]
  },
  { "title": "Regional API Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Regional GCP API Calls in $GcpRegion (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(clouddriver:google:api__count_total{instance=~\"$Instance\",scope=\"regional\",region=~\"$GcpRegion\"}[$__interval])) by (api), \"api\", \"$1\", \"api\", \"compute.(.*)\")",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Regional GCP API Latency in $GcpRegion (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(clouddriver:google:api__totalTime_total{instance=~\"$Instance\",scope=\"regional\",region=~\"$GcpRegion\"}[$__interval])) by (api) / sum(rate(clouddriver:google:api__count_total{instance=~\"$Instance\",scope=\"regional\",region=~\"$GcpRegion\"}[$__interval])) by (api), \"api\", \"$1\", \"api\", \"compute.(.*)\")",
     "legendFormat": "{{api}}"
    }
   ]
  },
  { "title": "Zonal API Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Zonal GCP API in $GcpRegion (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(sum(rate(clouddriver:google:api__count_total{instance=~\"$Instance\",scope=\"zonal\",zone=~\".*$GcpRegion.*\"}[$__interval])) by (zone, api), \"api\", \"$1\", \"api\", \"compute.(.*)\"), \"cell\", \"$1\", \"zone\", \".*-(.)\")",
     "legendFormat": "{{api}}/{{cell}}"
    }
   ]
  },
  {
   "title": "Zonal GCP API Latency in $GcpRegion (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(clouddriver:google:api__totalTime_total{instance=~\"$Instance\",scope=\"zonal\",zone=~\".*$GcpRegion.*\"}[$__interval])) by (api, zone) / sum(rate(clouddriver:google:api__count_total{instance=~\"$Instance\",scope=\"zonal\", zone=~\".*$GcpRegion.*\"}[$__interval])) by (api, zone), \"api\", \"$1\", \"api\", \"compute.(.*)\")",
     "legendFormat": "{{api}}/{{zone}}"
    }
   ]
  },
  { "title": "Batch Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "GCP Batch Size (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(clouddriver:google:batchSize{instance=~\"$Instance\"}[$__interval])) by (context), \"context\", \"$1$2\", \"context\", \"(.*)Caching(.*)\")",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "GCP Batch Count (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 6, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(clouddriver:google:batchExecute__count_total{instance=~\"$Instance\"}[$__interval])) by (context), \"context\", \"$1$2\", \"context\", \"(.*)Caching(.*)\")",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "GCP Batch Latency (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(clouddriver:google:batchExecute__totalTime_total{instance=~\"$Instance\"}[$__interval]) / rate(clouddriver:google:batchExecute__count_total{instance=~\"$Instance\"}[$__interval]), \"context\", \"$1$2\", \"context\", \"(.*)Caching(.*)\")",
     "legendFormat": "{{context}}"
    }
   ]
  },
  { "title": "GCP Operations Outcome", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Successful GCP Operations (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(clouddriver:google:operationWaits__count_total{instance=~\"$Instance\",status=\"DONE\"}[$__interval])) by (basePhase)",
     "legendFormat": "{{basePhase}}"
    }
   ]
  },
  {
   "title": "Failed GCP Operations (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(clouddriver:google:operationWaits__count_total{instance=~\"$Instance\",status!=\"DONE\"}[$__interval])) by (basePhase, scope) ",
     "legendFormat": "{{scope}}/{{basePhase}}"
    }
   ]
  },
  { "title": "Waiting GCP Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Global GCP Operation Waiting (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(rate(clouddriver:google:operationWaits__totalTime_total{instance=~\"$Instance\",scope=\"global\"}[$__interval])) by (basePhase) / sum(rate(clouddriver:google:operationWaits__count_total{instance=~\"$Instance\",scope=\"global\"}[$__interval])) by (basePhase) ",
     "legendFormat": "{{basePhase}}"
    }
   ]
  },
  {
   "title": "Regional GCP Operation Waiting in $GcpRegion (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(rate(clouddriver:google:operationWaits__totalTime_total{instance=~\"$Instance\",scope=\"regional\",region=~\"$GcpRegion\"}[$__interval])) by (region, basePhase) / sum(rate(clouddriver:google:operationWaits__count_total{instance=~\"$Instance\",scope=\"regional\",region=~\"$GcpRegion\"}[$__interval])) by (region, basePhase) ",
     "legendFormat": "{{basePhase}}//{{region}}"
    }
   ]
  },
  {
   "title": "Zonal GCP Operation Waiting in $GcpRegion (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(clouddriver:google:operationWaits__totalTime_total{instance=~\"$Instance\",scope=\"zonal\",zone=~\".*$GcpRegion.*\"}[$__interval]), \"cell\", \"$1\", \"zone\", \".*-(.)\")) by (basePhase, cell) / sum(label_replace(rate(clouddriver:google:operationWaits__count_total{instance=~\"$Instance\",scope=\"zonal\",zone=~\".*$GcpRegion.*\"}[$__interval]), \"cell\", \"$1\", \"zone\", \".*-(.)\")) by (basePhase, cell) ",
     "legendFormat": "{{basePhase}}/{{cell}}"
    }
   ]
  },
  { "title": "Started GCP Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Global GCP Operations Started (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(clouddriver:google:operationWaitRequests{instance=~\"$Instance\",scope=\"global\"}[$__interval])) by (basePhase)",
     "legendFormat": "{{basePhase}}"
    }
   ]
  },
  {
   "title": "Regional GCP Operations Started in $GcpRegion (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(clouddriver:google:operationWaitRequests{instance=~\"$Instance\",scope=\"regional\",region=~\"$GcpRegion\"}[$__interval])) by (basePhase)",
     "legendFormat": "{{basePhase}}"
    }
   ]
  },
  {
   "title": "Zonal GCP Operations Started in $GcpRegion (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(clouddriver:google:operationWaitRequests{instance=~\"$Instance\",scope=\"zonal\",zone=~\".*$GcpRegion.*\"}[$__interval])) by (basePhase)",
     "legendFormat": "{{basePhase}}"
    }
   ]
  },
  { "title": "Safe Retry Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Retryable Global GCP (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(clouddriver:google:safeRetry__count_total{instance=~\"$Instance\",scope=\"global\"}[$__interval]), \"operation\", \"$1\", \"operation\", \"compute.(.*)\")) by (operation, phase)",
     "legendFormat": "{{phase}}.{{operation}}"
    }
   ]
  },
  {
   "title": "Retryable Regional GCP in $GcpRegion (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(clouddriver:google:safeRetry__count_total{instance=~\"$Instance\",scope=\"regional\",region=~\"$GcpRegion\"}[$__interval])) by (instance, phase, operation), \"operation\", \"$1\", \"operation\", \"compute.(.*)\")",
     "legendFormat": "{{phase}}.{{operation}}"
    }
   ]
  },
  {
   "title": "Retryable Zonal GCP in $GcpRegion (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(sum(rate(clouddriver:google:safeRetry__count_total{instance=~\"$Instance\",scope=\"zonal\",zone=~\".*$GcpRegion.*\"}[$__interval])) by (instance, phase, operation, cell), \"operation\", \"$1\", \"operation\", \"compute.(.*)\"), \"cell\", \"$1\", \"zone\", \".*-(.)\")",
     "legendFormat": "{{phase}}.{{operation}}/{{cell}}"
    }
   ]
  },
  { "title": "Safe Retry Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Retryable Global GCP Latency (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(clouddriver:google:safeRetry__totalTime_total{instance=~\"$Instance\",scope=\"global\"}[$__interval])) by (operation, phase) / sum(rate(clouddriver:google:safeRetry__count_total{instance=~\"$Instance\",scope=\"global\"}[$__interval])) by (operation, phase), \"operation\", \"$1\", \"operation\", \"compute.(.*)\")",
     "legendFormat": "{{phase}}.{{operation}}"
    }
   ]
  },
  {
   "title": "Retryable Regional GCP Latency in $GcpRegion (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 85 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(clouddriver:google:safeRetry__totalTime_total{instance=~\"$Instance\",scope=\"regional\",region=~\"$GcpRegion\"}[$__interval])) by (operation, phase) / sum(rate(clouddriver:google:safeRetry__count_total{instance=~\"$Instance\",scope=\"regional\",region=~\"$GcpRegion\"}[$__interval])) by (operation, phase), \"operation\", \"$1\", \"operation\", \"compute.(.*)\")",
     "legendFormat": "{{phase}}.{{operation}}"
    }
   ]
  },
  {
   "title": "Retryable Zonal GCP Latency in $GcpRegion (clouddriver, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 85 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(label_replace(sum(rate(clouddriver:google:safeRetry__totalTime_total{instance=~\"$Instance\",scope=\"zonal\",zone=~\".*$GcpRegion.*\"}[$__interval])) by (operation, phase, zone) / sum(rate(clouddriver:google:safeRetry__count_total{instance=~\"$Instance\",scope=\"zonal\",zone=~\".*$GcpRegion.*\"}[$__interval])) by (operation, phase, zone), \"cell\", \"$1\", \"zone\", \".*-(.)\")) by (phase, operation, cell), \"operation\", \"$1\", \"operation\", \"compute.(.*)\")",
     "legendFormat": "{{phase}}.{{operation}}/{{cell}}"
    }
   ]
  },
  { "title": "Google Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Google Storage Service Calls (front50, $Front50Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(front50:google:storage:invocation__count_total{instance=~\"$Front50Instance\"}[$__interval])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Google Storage Service Latency (front50, $Front50Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(rate(front50:google:storage:invocation__totalTime_total{instance=~\"$Front50Instance\"}[$__interval])) by (method) / sum(rate(front50:google:storage:invocation__count_total{instance=~\"$Front50Instance\"}[$__interval])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}