{
 "title": "Igor Microservice",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{job=\"igor\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Resilience4J Open",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (\n  max_over_time(resilience4j_circuitbreaker_state{job=\"igor\", state=~\".*open\", instance=~\"$Instance\"}[$__interval])\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resilience4J Failure Rate ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "failures/s" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(resilience4j_circuitbreaker_failure_rate{job=\"igor\", instance=~\"$Instance\"}[$__interval])\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resilience4J Half-Open",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Poll Monitor req/s",
   "type": "graph",
   "description": "The requests/s for Poll Monitor invocations.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (monitor) (\n  rate(pollingMonitor_pollTiming_seconds_count{job=\"igor\", instance=~\"$Instance\"}[$__interval])\n)",
     "legendFormat": "{{monitor}}"
    }
   ]
  },
  {
   "title": "Poll Monitor Latency",
   "type": "graph",
   "description": "The requests/s for Poll Monitor invocations.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (monitor) (rate(pollingMonitor_pollTiming_seconds_sum{job=\"igor\", instance=~\"$Instance\"}[$__interval]))\n/\nsum by (monitor) (rate(pollingMonitor_pollTiming_seconds_count{job=\"igor\", instance=~\"$Instance\"}[$__interval]))",
     "legendFormat": "{{monitor}}"
    }
   ]
  },
  {
   "title": "Failed Polls",
   "type": "graph",
   "description": "Failed Poll requests per sec by monitor and partition. ",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (monitor, partition) (\n  rate(pollingMonitor_failed_total{job=\"igor\", instance=~\"$Instance\"}[$__interval])\n)",
     "legendFormat": "{{monitor}} / {{partition}}"
    }
   ]
  },
  {
   "title": "Docker Images Retrieved",
   "type": "graph",
   "description": "The requests/s to retrieve docker images by account. This triggers the pipelines.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (account) (\n  rate(pollingMonitor_docker_retrieveImagesByAccount_seconds_count{job=\"igor\", instance=~\"$Instance\"}[$__interval])\n)",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Items over Threshold",
   "type": "graph",
   "description": "This gauge tracks the circuit breaker (threshold) for new items (docker, etc).\n\nGenerally the value should always be null or 0.\n\nA positive value indicates the threshold has been exceeded and the circuit breaker tripped. This means Igor will no longer notify Echo of new items and pipelines won't be triggered.\n\nThe circuit breaker can be reset by performing a 'fast-forward' or adjusting the the threshold item limit value and redeploying Igor.\n\nThe threshold can be exceeded due to loss of cache (abnormal) or large influx of new items.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (monitor, partition) (\n  max_over_time(pollingMonitor_itemsOverThreshold{job=\"igor\", instance=~\"$Instance\"}[$__interval])\n)",
     "legendFormat": "{{ monitor }} / {{ partition }}"
    }
   ]
  },
  {
   "title": "5xx Controller Invocations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, method, statusCode) (\n  rate(controller_invocations_total{job=~\"igor\",status=\"5xx\", instance=~\"$Instance\"}[$__interval])\n)",
     "legendFormat": "{{statusCode}}/{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Controller Invocations by Method",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, method) (\n  rate(controller_invocations_total{job=~\"igor\", instance=~\"$Instance\"}[$__interval])\n)",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Controller Invocation Latency by Method",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (controller, method) (rate(controller_invocations_seconds_sum{job=~\"igor\", instance=~\"$Instance\"}[$__interval]))\n/\nsum by (controller, method) (rate(controller_invocations_seconds_count{job=~\"igor\", instance=~\"$Instance\"}[$__interval]))",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (id) (\n  max_over_time(jvm_memory_used_bytes{job=\"igor\", area=\"heap\", instance=~\"$Instance\"}[$__interval])\n)",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}