{
 "title": "Spinnaker Minimalist",
 "tags": [ "spinnaker" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Resilience4J Open",
   "type": "graph",
   "description": "https://resilience4j.readme.io/docs/circuitbreaker",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"open\"}) by (job, metricGroup, metricType)",
     "legendFormat": "{{ job }}/{{metricGroup}}({{metricType}})"
    }
   ]
  },
  {
   "title": "Resilience4J Half-Open",
   "type": "graph",
   "description": "https://resilience4j.readme.io/docs/circuitbreaker",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"half_open\"}) by (job, metricGroup, metricType)",
     "legendFormat": "{{ job }} /{{metricType}}({{metricGroup}})"
    }
   ]
  },
  {
   "title": "5xx Invocation Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(controller_invocations_total{container=\"clouddriver\",status=\"5xx\"}[$__interval])) by (controller, statusCode), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
     "legendFormat": "Clouddriver/{{statusCode}}/{{controller}}"
    },
    {
     "expr": "label_replace(sum(rate(controller_invocations_total{container=\"echo\",status=\"5xx\"}[$__interval])) by (controller, statusCode), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
     "legendFormat": "Echo/{{statusCode}}/{{controller}}"
    },
    {
     "expr": "label_replace(sum(rate(controller_invocations_total{container=\"fiat\",status=\"5xx\"}[$__interval])) by (controller, statusCode), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
     "legendFormat": "Fiat/{{statusCode}}/{{controller}}"
    },
    {
     "expr": "label_replace(sum(rate(controller_invocations_total{container=\"front50\",status=\"5xx\"}[$__interval])) by (controller, statusCode), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
     "legendFormat": "Front50/{{statusCode}}/{{controller}}"
    },
    {
     "expr": "label_replace(sum(rate(controller_invocations_total{container=\"gate\",status=\"5xx\"}[$__interval])) by (controller, statusCode), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
     "legendFormat": "Gate/{{statusCode}}/{{controller}}"
    },
    {
     "expr": "label_replace(sum(rate(controller_invocations_total{container=\"igor\",status=\"5xx\"}[$__interval])) by (controller, statusCode), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
     "legendFormat": "Igor/{{statusCode}}/{{controller}}"
    },
    {
     "expr": "label_replace(sum(rate(controller_invocations_total{container=\"orca\",status=\"5xx\"}[$__interval])) by (controller, statusCode), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
     "legendFormat": "Orca/{{statusCode}}/{{controller}}"
    },
    {
     "expr": "label_replace(sum(rate(controller_invocations_total{container=\"rosco\",status=\"5xx\"}[$__interval])) by (controller, statusCode), \"controller\", \"$1\", \"controller\", \"(.*)Controller\")",
     "legendFormat": "Rosco/{{statusCode}}/{{controller}}"
    }
   ]
  },
  {
   "title": "Active Stages per Type/Platform (orca)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(stage_invocations_total[$__interval])) by (instance, type, cloudProvider)",
     "legendFormat": "{{type}}/{{cloudProvider}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Completed Stages per Type/Platform (orca)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(stage_invocations_total[$__interval])) by (cloudProvider, type)",
     "legendFormat": "{{cloudProvider}} :: {{type}}"
    }
   ]
  },
  {
   "title": "Stage Duration > 5m per Time-Bucket/Platform (orca)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(stage_invocations_duration_total{bucket!=\"lt5m\"}[$__interval])) by (cloudProvider, percentile)",
     "legendFormat": "{{percentile}}/{{cloudProvider}}"
    }
   ]
  },
  {
   "title": "Pipelines Triggered (echo)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pipelines_triggered_total[$__interval])) by (application,monitor)",
     "legendFormat": "{{application}} :: {{ monitor }}"
    }
   ]
  },
  {
   "title": "Bake Activity (rosco)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(bakesActive)", "legendFormat": "Active" },
    {
     "expr": "sum(rate(bakesRequested[$__interval])) by (flavor)",
     "legendFormat": "Request({{flavor}})"
    },
    {
     "expr": "-1 * sum(rate(bakesCompleted{success=\"false\"}[$__interval])) by (region)",
     "legendFormat": "Failed {{region}}"
    }
   ]
  },
  {
   "title": "Item Cache Size (front50)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(storageServiceSupport_cacheSize) by (objectType)",
     "legendFormat": "{{objectType}}"
    }
   ]
  },
  {
   "title": "Execution Count (clouddriver)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(executionCount_total[$__interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Execution Latency (clouddriver)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(rate(executionTime_seconds_sum[$__interval])) by (instance) / sum(rate(executionTime_seconds_count[$__interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}