{
 "title": "Orca Microservice",
 "tags": [ "spinnaker" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "spinSvc", "query": "orca" },
   {
    "name": "job",
    "query": "label_values(up{job=~\".*$spinSvc.*\"}, job)"
   },
   {
    "name": "Instance",
    "query": "label_values(up{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "5xx Invocation Errors (orca, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_total{job=~\"$job\", instance=~\"$Instance\", status=\"5xx\"}[$__interval])) by (controller, method, status)",
     "legendFormat": "{{statusCode}}/{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Stage Durations > 5m per Time-Bucket/Platform (orca, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(stage_invocations_duration_total{job=~\"$job\", instance=~\"$Instance\", bucket!=\"lt5m\"}[$__interval])) by (stageType, cloudProvider, bucket)",
     "legendFormat": "{{bucket}}/{{cloudProvider}}/{{stageType}}"
    }
   ]
  },
  {
   "title": "Ok Http Calls by Status Code (orca, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(okhttp_requests_seconds_count{job=~\"$job\",instance=~\"$Instance\"}[$__interval])) by (statusCode)",
     "legendFormat": "{{statusCode}}"
    }
   ]
  },
  {
   "title": "Ok Http Calls Latency by Request Host (orca, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(okhttp_requests_seconds_sum{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (requestHost)\n/\nsum(rate(okhttp_requests_seconds_count{job=\"$job\", instance=~\"$Instance\"}[$__interval])) by (requestHost)",
     "legendFormat": "{{requestHost}}"
    }
   ]
  },
  {
   "title": "Controller Invocations by Method (orca, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_total{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (controller, method)",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Controller Invocation Latency by Method (orca, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_seconds_sum{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (controller, method)\n/\nsum(rate(controller_invocations_total{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (controller, method)",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Active Stages per Type/Platform (orca, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(stage_invocations_total{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (cloudProvider, type)",
     "legendFormat": "{{type}}/{{cloudProvider}}"
    }
   ]
  },
  {
   "title": "Stages Completed per Type/Platform (orca, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(stage_invocations_duration_total{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (cloudProvider, stageType)",
     "legendFormat": "{{stageType}}/{{cloudProvider}}"
    }
   ]
  },
  {
   "title": "Blocked Queues (orca, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(threadpool_blockingQueueSize{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Zombie Queues (orca, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (application) (queue_zombies_total{job=~\"$job\", instance=~\"$Instance\"})",
     "legendFormat": "{{ application }}"
    }
   ]
  },
  {
   "title": "Active Threads (orca, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(threadpool_activeCount{job=~\"$job\", instance=~\"$Instance\"}) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "ThreadPool Size (orca, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(threadpool_poolSize{job=~\"$job\", instance=~\"$Instance\"}) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Queue Depth (orca, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(queue_depth{job=~\"$job\", instance=~\"$Instance\"}) by (instance)",
     "legendFormat": "Queued"
    },
    {
     "expr": "sum(queue_ready_depth{job=~\"$job\", instance=~\"$Instance\"}) by (instance)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(queue_unacked_depth{job=~\"$job\", instance=~\"$Instance\"}) by (instance)\n",
     "legendFormat": "In-Process"
    }
   ]
  },
  {
   "title": "Queue Errors (orca, $Instance)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(queue_orphaned_messages{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (job)\n",
     "legendFormat": "Orphaned"
    }
   ]
  },
  {
   "title": "Message Lag Time (orca, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(queue_message_lag_seconds_count{job=~\"$job\", instance=~\"$Instance\"}[$__interval])",
     "legendFormat": "messages {{ instance }}"
    },
    {
     "expr": "rate(queue_message_lag_seconds_sum{job=~\"$job\", instance=~\"$Instance\"}[$__interval])\n/\nrate(queue_message_lag_seconds_count{job=~\"$job\", instance=~\"$Instance\"}[$__interval])",
     "legendFormat": "lag time {{ instance }}"
    }
   ]
  },
  {
   "title": "Pushed Message Summary (orca, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(queue_pushed_messages_total{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (instance)",
     "legendFormat": "Pushed/{{ instance }}"
    },
    {
     "expr": "sum(rate(queue_acknowledged_messages_total{instance=~\"$Instance\"}[$__interval])) by (instance)",
     "legendFormat": "Acknowledged/{{ instance }}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage (orca, $Instance)",
   "type": "graph",
   "description": "TODO: Check source code for why this metric isn't published for Orca",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$job\", instance=~\"$Instance\", area=\"heap\"}) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}