{
 "title": "Rosco Microservice",
 "tags": [ "spinnaker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "spinSvc", "query": "rosco" },
   {
    "name": "job",
    "query": "label_values(up{job=~\".*$spinSvc.*\"}, job)"
   },
   {
    "name": "Instance",
    "query": "label_values(up{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Controller 5xx Errors (rosco, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_total{job=\"$job\",instance=~\"$Instance\",status=\"5xx\"}[$__interval])) by (controller, method, statusCode)",
     "legendFormat": "{{statusCode}}/{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Controller Invocations by Method (rosco, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_total{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (controller, method)",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Controller Invocation Latency by Method (rosco, $Instance)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(rate(controller_invocations_seconds_sum{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (controller, method)\n/\nsum(rate(controller_invocations_seconds_count{job=~\"$job\", instance=~\"$Instance\"}[$__interval])) by (controller, method)",
     "legendFormat": "{{controller}}/{{method}}"
    }
   ]
  },
  {
   "title": "Bakes Completed (rosco, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bakesCompleted_duration_seconds_sum{instance=~\"$Instance\"}[$__interval])) by (region)\n/\nsum(rate(bakesCompleted_duration_seconds_count{instance=~\"$Instance\"}[$__interval])) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Bake Requests and Failures  (rosco, $Instance)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bakesActive{instance=~\"$Instance\"}) by (instance)",
     "legendFormat": "Active/{{instance}}"
    },
    {
     "expr": "sum(rate(bakesRequested{instance=~\"$Instance\"}[$__interval])) by (flavor)",
     "legendFormat": "Request/{{flavor}}"
    },
    {
     "expr": "-1 * sum(rate(bakesCompleted{instance=~\"$Instance\",success=\"false\"}[$__interval])) by (region)",
     "legendFormat": "Failed/{{region}}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage (rosco, $Instance)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{job=~\"$job\", instance=~\"$Instance\",area=\"heap\"}) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}